# Generated by Django 5.2.13 on 2026-04-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_promotionlibrary_crop_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmaster',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
