# Generated by Django 5.2.13 on 2026-05-02 11:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cropmaster_reference_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionlibrary',
            name='related_product',
        ),
        migrations.AddField(
            model_name='promotionlibrary',
            name='category',
            field=models.CharField(choices=[('Product', 'Product'), ('Tagline', 'Tagline'), ('WhatsApp', 'WhatsApp'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Schedule', 'Schedule'), ('Testimonial', 'Testimonial'), ('YouTube Playlist', 'YouTube Playlist')], default='Product', max_length=50),
        ),
        migrations.AddField(
            model_name='promotionlibrary',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='core.productmaster'),
        ),
        migrations.AddField(
            model_name='territory',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
