# Generated by Django 5.2.13 on 2026-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cropseason_total_expenses_rs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropseason',
            name='area_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
