# Generated by Django 5.2.13 on 2026-06-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cropseason_area_acres_plot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='calculated_area_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
