# Generated by Django 5.2.13 on 2026-06-11 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_farmer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmaster',
            name='marathi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_rates', to='core.cropmaster')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('crop', 'date')},
            },
        ),
    ]
