# Generated by Django 5.2.13 on 2026-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cropmaster_marathi_name_marketrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrate',
            name='inward_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
