# Generated by Django 5.2.13 on 2026-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_marketrate_inward_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksendbatch',
            name='frequency',
            field=models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], default='Once', max_length=20),
        ),
        migrations.AddField(
            model_name='bulksendbatch',
            name='next_execution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulksendbatch',
            name='scheduled_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulksendbatch',
            name='scheduled_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
