# Generated by Django 5.2.13 on 2026-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='source',
            field=models.CharField(blank=True, default='InApp', max_length=255, null=True),
        ),
    ]
