# Generated by Django 5.2.13 on 2026-08-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_farmer_acquisition_date_alter_farmer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salesapp_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
