# Generated by Django 5.2.13 on 2026-08-04 12:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_salesapp_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='gps_validation_mode',
            field=models.CharField(choices=[('Strict', 'Strict'), ('Warning', 'Warning')], default='Warning', help_text='Strict blocks save outside radius; Warning flags visit and permits save', max_length=20),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='visit_radius_meters',
            field=models.IntegerField(default=150, help_text='Maximum distance in meters for verified visit'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='dose_unit',
            field=models.CharField(blank=True, default='g/L', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.plot'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.productmaster'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='review_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Needs Review', 'Needs Review'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='channel',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Internal', 'Internal')], default='Internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='salesapp_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('Outgoing', 'Outgoing'), ('Incoming', 'Incoming')], default='Outgoing', max_length=20)),
                ('call_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('outcome', models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Follow-up Required', 'Follow-up Required'), ('No Answer', 'No Answer'), ('Busy', 'Busy'), ('Switched Off', 'Switched Off'), ('Complaint', 'Complaint'), ('Other', 'Other')], default='Other', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='core.farmer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('Product Demonstration', 'Product Demonstration'), ('Crop Advisory', 'Crop Advisory'), ('Issue Resolution', 'Issue Resolution'), ('Routine Visit', 'Routine Visit'), ('Complaint Investigation', 'Complaint Investigation'), ('New Farmer Registration', 'New Farmer Registration'), ('Collection', 'Collection'), ('Other', 'Other')], default='Routine Visit', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Outside Radius', 'Outside Radius'), ('Pending Check-Out', 'Pending Check-Out'), ('Completed', 'Completed')], default='Verified', max_length=30)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distance_from_plot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inside_radius', models.BooleanField(default=True)),
                ('photo_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='core.farmer')),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to='core.plot')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Internal', 'Internal')], default='Internal', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('delivery_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='VisitPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.fieldvisit')),
            ],
        ),
    ]
