# Generated by Django 5.2.13 on 2026-08-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_update_user_hierarchy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='act_farmer_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='act_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='cropseason',
            name='season_plot_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='cropseason',
            name='season_crop_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='farmer',
            name='farmer_staff_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='farmer',
            name='farmer_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='farmer',
            name='farmer_date_added_idx',
        ),
        migrations.RemoveIndex(
            model_name='plot',
            name='plot_farmer_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendation',
            name='rec_farmer_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendation',
            name='rec_user_time_idx',
        ),
        migrations.AlterField(
            model_name='bulksendbatch',
            name='channel',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Internal', 'Internal')], default='Internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='territory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='visitphoto',
            name='photo_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visitphoto',
            name='thumbnail_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
