# Generated by Django 5.2.13 on 2026-08-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_activitylog_act_farmer_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='active_sms_provider',
            field=models.CharField(choices=[('MSG91', 'MSG91'), ('STPL', 'STPL')], default='STPL', max_length=20),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='interakt_template_name',
            field=models.CharField(blank=True, default='farmer_alert_01', help_text='Default generic template name for WhatsApp broadcasts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='stpl_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='stpl_api_url',
            field=models.CharField(blank=True, default='https://www.smsgatewayhub.com/api/mt/SendSMS', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='stpl_sender_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
