# Generated by Django 5.2.13 on 2026-08-22 11:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appconfiguration_active_sms_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FieldStaff', 'Field Staff'), ('TerritoryManager', 'Territory Manager'), ('ZonalManager', 'Zonal Manager'), ('Admin', 'Admin'), ('ContentTeam', 'Content Team'), ('ContentAdmin', 'Content Admin')], default='FieldStaff', max_length=20),
        ),
        migrations.CreateModel(
            name='ContentTeamSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(default='Internal', max_length=20)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promotionlibrary')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sends', to='core.farmer')),
                ('sent_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPriceImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('records_processed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=20)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCorridor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('route_polyline', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_corridors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRiskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_type', models.CharField(max_length=100)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operator', models.CharField(max_length=10)),
                ('advisory_message', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cropmaster')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cropstage')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecast_summary', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(default='IMD', max_length=100)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='core.plot')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPriceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('market_name', models.CharField(max_length=255)),
                ('commodity_name', models.CharField(max_length=255)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cropmaster')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.marketpriceimportbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['commodity_name', 'date'], name='core_market_commodi_65c128_idx')],
                'unique_together': {('date', 'market_name', 'commodity_name')},
            },
        ),
    ]
