# Generated by Django 5.2.13 on 2026-08-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_user_role_contentteamsend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='content_admin_weekly_promotion_limit',
            field=models.IntegerField(default=2, help_text='Maximum promotions a farmer can receive per week from the Content Team'),
        ),
    ]
