# Generated by Django 5.2.13 on 2026-08-26 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_appconfiguration_content_admin_weekly_promotion_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(help_text='The exact string imported from external data', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cropmaster')),
            ],
        ),
    ]
