# Generated by Django 5.2.13 on 2026-09-03 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_commoditymapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('region_applicability', models.CharField(blank=True, help_text="States or regions where this festival heavily impacts markets (e.g. 'Maharashtra', 'All India')", max_length=255, null=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('name', 'year')},
            },
        ),
    ]
