# Generated by Django 5.2.13 on 2026-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmaster',
            name='reference_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
